name: todo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cronet_http: ^1.3.4
  cupertino_http: ^2.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  get_it: ^8.0.3
  http: ^1.4.0
  http_interceptor: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  video_player: ^2.9.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true